-- AlterTable
ALTER TABLE "SpendEvent" ADD COLUMN "promptTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SpendEvent" ADD COLUMN "completionTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SpendEvent" ADD COLUMN "totalTokens" INTEGER NOT NULL DEFAULT 0;
